name: lint

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  eslint:
    name: Lint TypeScript/JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Set up Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 16
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Run eslint
        run: npm run lint

  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Set up problem matcher
        uses: xt0rted/markdownlint-problem-matcher@b643b0751c371f357690337d4549221347c0e1bc # tag=v1.1.0
      - name: Run markdownlint
        run: npx --package markdownlint-cli markdownlint '**/*.md' --ignore node_modules
